"""ajout table enfants

Revision ID: 13faee471184
Revises: 1efa2663b2d8
Create Date: 2025-07-24 20:40:24.222676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13faee471184'
down_revision: Union[str, Sequence[str], None] = '1efa2663b2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enfants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('postnom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('sobriquet', sa.String(length=100), nullable=True),
    sa.Column('sexe', sa.SmallInteger(), nullable=False),
    sa.Column('age_enfant', sa.SmallInteger(), nullable=False),
    sa.Column('niveau_scol_regroupe', sa.SmallInteger(), nullable=False),
    sa.Column('date_enregistrement', sa.DateTime(), nullable=True),
    sa.Column('score_initial', sa.Float(), nullable=True),
    sa.Column('statut_risque', sa.String(length=30), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('foyer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['foyer_id'], ['maison_accueil.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enfants_id'), 'enfants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enfants_id'), table_name='enfants')
    op.drop_table('enfants')
    # ### end Alembic commands ###
