"""ajout table maison_accuecicl

Revision ID: 1efa2663b2d8
Revises: a158c3675f10
Create Date: 2025-07-24 15:51:14.691899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efa2663b2d8'
down_revision: Union[str, Sequence[str], None] = 'a158c3675f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maison_accueil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_foyer', sa.String(length=50), nullable=False),
    sa.Column('nom_foyer', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('age_chef', sa.Integer(), nullable=False),
    sa.Column('sexe_chef', sa.Integer(), nullable=False),
    sa.Column('niveau_education_mere_recod', sa.Integer(), nullable=False),
    sa.Column('etat_logement', sa.String(length=50), nullable=False),
    sa.Column('nb_pieces_cat', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maison_accueil_id'), 'maison_accueil', ['id'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('adresse', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=False),
    sa.Column('date_creation', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_organisations_id'), 'organisations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisations_id'), table_name='organisations')
    op.drop_table('organisations')
    op.drop_index(op.f('ix_maison_accueil_id'), table_name='maison_accueil')
    op.drop_table('maison_accueil')
    # ### end Alembic commands ###
