"""ajout modif suivis 

Revision ID: 468b179b236b
Revises: 999d5991273b
Create Date: 2025-07-25 01:41:48.799772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468b179b236b'
down_revision: Union[str, Sequence[str], None] = '999d5991273b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suivis', sa.Column('quintile_bien_etre_x', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suivis', 'quintile_bien_etre_x')
    # ### end Alembic commands ###
