"""ajout table suivis

Revision ID: 999d5991273b
Revises: 4911123d6b7f
Create Date: 2025-07-25 01:34:27.612322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999d5991273b'
down_revision: Union[str, Sequence[str], None] = '4911123d6b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suivis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enfant_id', sa.Integer(), nullable=False),
    sa.Column('date_suivi', sa.DateTime(), nullable=True),
    sa.Column('heures_total_travail', sa.Integer(), nullable=False),
    sa.Column('scol_actuelle', sa.Boolean(), nullable=False),
    sa.Column('difficulte_fonctionnelle', sa.Boolean(), nullable=False),
    sa.Column('souffre_punition_physique', sa.Boolean(), nullable=False),
    sa.Column('travail_enfant_global', sa.Boolean(), nullable=False),
    sa.Column('niveau_scol_regroupe', sa.SmallInteger(), nullable=False),
    sa.Column('favorable_correction_physique', sa.Boolean(), nullable=False),
    sa.Column('score_suivi', sa.Float(), nullable=False),
    sa.Column('statut_risque', sa.String(length=30), nullable=False),
    sa.Column('commentaire_agent', sa.Text(), nullable=True),
    sa.Column('conseil_personnalise', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['enfant_id'], ['enfants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suivis_id'), 'suivis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suivis_id'), table_name='suivis')
    op.drop_table('suivis')
    # ### end Alembic commands ###
